/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shamazon;

import java.awt.image.BufferedImage;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author Charles
 */
public class ListingPreviewPanel extends javax.swing.JPanel {

    /**
     * The listing this listingPreviewPanel shows
     */
    private Listing listingPreview;
    
    /**
     * The shopping cart referenced by this listing
     */
    private ShoppingCart shopCart;
    
    /**
     * Reference to the listingBrowser
     */
    private ListingBrowser listBrowser;
    
    /**
     * Creates new form ListngPreviewPanel
     */
    public ListingPreviewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        ListingNameLabel = new javax.swing.JLabel();
        ListingImageLabel = new javax.swing.JLabel();
        ListingDescLabel = new javax.swing.JLabel();
        ListingPriceLabel = new javax.swing.JLabel();
        AddToCartButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ListingNameLabel.setText("ListingName");

        ListingImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShamazonResources/ClientImages/ImageMissing.png"))); // NOI18N
        ListingImageLabel.setMaximumSize(new java.awt.Dimension(150, 150));
        ListingImageLabel.setMinimumSize(new java.awt.Dimension(150, 150));
        ListingImageLabel.setPreferredSize(new java.awt.Dimension(150, 150));

        ListingDescLabel.setText("ListingDescription");
        ListingDescLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ListingPriceLabel.setText("Price: ");

        AddToCartButton.setText("Add to cart");
        AddToCartButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddToCartButtonActionPerformed(evt);
            }
        });

        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                deleteButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListingImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListingDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ListingNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddToCartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ListingPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListingImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ListingNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListingDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddToCartButton)
                            .addComponent(ListingPriceLabel)
                            .addComponent(EditButton)
                            .addComponent(deleteButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the shopping cart reference of this object
     * @param cart 
     */
    public void SetShoppingCart(ShoppingCart cart)
    {
        shopCart = cart;
    }
    
    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed
        //Check if the user is the owner of this listing
        
        shopCart.AddListing(listingPreview);
        
    }//GEN-LAST:event_AddToCartButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EditButtonActionPerformed
    {//GEN-HEADEREND:event_EditButtonActionPerformed
        EditListing(listingPreview);
    }//GEN-LAST:event_EditButtonActionPerformed

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_deleteButtonMouseClicked
    {//GEN-HEADEREND:event_deleteButtonMouseClicked
        UserAccount owner = listingPreview.GetOwner();
        owner.RemovePostedListing(listingPreview);
        
        try
        {
            DatabaseManager.RemoveObjectFromDatabase(listingPreview, "Listings");
            DatabaseManager.UpdateObjectInDatabase(owner, "UserAccounts");
        }
        catch(SQLException e)
        {
           
        }
        
        // get the UserListingDialog
        try
        {
            UserListingDialog listingDialog = (UserListingDialog)this.getParent().getParent().getParent().getParent().getParent().getParent().getParent();
            listingDialog.RemoveListing(listingPreview);
            listingDialog.RefreshListings();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_deleteButtonMouseClicked
    
    /**
     * Used to call the editor when editing listings. I honestly do not know when we call it from this class/form.
     * @param list 
     */
    public void EditListing(Listing list)
    {
       //Edit a given listing provided it is owned by the user and not sold
       EditorDialog editor = new EditorDialog(new javax.swing.JFrame(), true,false);
       editor.LoadListing(list);
       editor.setVisible(true);
       editor.creating = false;
       
       try
       {
           DatabaseManager.UpdateObjectInDatabase(list.GetOwner(), "Listings");
           LoadListingToPanel((Listing)DatabaseManager.GetUpdatedObjectFromDatabase(list, "Listings"), listBrowser);
       }
       catch(SQLException e)
       {
           
       }
    }
    
    /**
     * Loads the edit button on a previewPanel and removes the add to cart button.
     */
    public void LoadEdit()
    {
        EditButton.setVisible(true);
        AddToCartButton.setVisible(false);
        deleteButton.setVisible(true);
    }
    
    /**
     * Loads the listing to the panel labels.
     * @param list
     * @param listBrow 
     */
    public void LoadListingToPanel(Listing list, ListingBrowser listBrow)
    {
        deleteButton.setVisible(false);
        EditButton.setVisible(false);
        listingPreview = list;
        listBrowser = listBrow;
        
        //Set name, description and price for each of the listing properties
        ListingNameLabel.setText(list.GetName());
        ListingDescLabel.setText(list.GetDescription());
        ListingPriceLabel.setText("Price: " + Float.toString(list.GetPrice()));
        //make sure there is an image to show
        if(list.GetListingImage() != null)
        {
            //Get bufferedImage from the listing
            ImageIcon listImage = list.GetListingImage();
            
            //Create a previewIcon from a scaled instance of listImage
            ImageIcon previewIcon = new ImageIcon(listImage.getImage().getScaledInstance(ListingImageLabel.getPreferredSize().width,ListingImageLabel.getPreferredSize().height,0));
            
            //Set label to previewIcon.
            ListingImageLabel.setIcon(previewIcon);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel ListingDescLabel;
    private javax.swing.JLabel ListingImageLabel;
    private javax.swing.JLabel ListingNameLabel;
    private javax.swing.JLabel ListingPriceLabel;
    private javax.swing.JButton deleteButton;
    // End of variables declaration//GEN-END:variables
}
