/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shamazon;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Charles
 */
public class ListingPreviewPanel extends javax.swing.JPanel {

    /**
     * The listing this listingPreviewPanel shows
     */
    private Listing listingPreview;
    
    /**
     * The shopping cart referenced by this listing
     */
    private ShoppingCart shopCart;
    
    /**
     * Reference to the listingBrowser
     */
    private ListingBrowser listBrowser;
    
    /**
     * Creates new form ListngPreviewPanel
     */
    public ListingPreviewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        ListingNameLabel = new javax.swing.JLabel();
        ListingImageLabel = new javax.swing.JLabel();
        ListingDescLabel = new javax.swing.JLabel();
        ListingPriceLabel = new javax.swing.JLabel();
        AddToCartButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ListingNameLabel.setText("ListingName");

        ListingImageLabel.setText("ListingImage");

        ListingDescLabel.setText("ListingDescription");
        ListingDescLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ListingPriceLabel.setText("Price: ");

        AddToCartButton.setText("Add to cart");
        AddToCartButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddToCartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListingImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListingDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListingNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddToCartButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ListingPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListingImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ListingNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListingDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddToCartButton)
                            .addComponent(ListingPriceLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the shopping cart reference of this object
     * @param cart 
     */
    public void SetShoppingCart(ShoppingCart cart)
    {
        shopCart = cart;
    }
    
    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed
        //Check if the user is the owner of this listing
        
        shopCart.AddListing(listingPreview);
        
    }//GEN-LAST:event_AddToCartButtonActionPerformed
    
    public void LoadListingToPanel(Listing list, ListingBrowser listBrow)
    {
        listingPreview = list;
        listBrowser = listBrow;
        
        //Set name, description and price for each of the listing properties
        ListingNameLabel.setText(list.GetName());
        ListingDescLabel.setText(list.GetDescription());
        ListingPriceLabel.setText("Price: " + Float.toString(list.GetPrice()));
        //make sure there is an image to show
        if(list.GetListingImage() != null)
        {
            //Get bufferedImage from the listing
            BufferedImage listImage = list.GetListingImage();
            
            //Create a previewIcon from a scaled instance of listImage
            ImageIcon previewIcon = new ImageIcon(listImage.getScaledInstance(ListingImageLabel.getWidth(),ListingImageLabel.getHeight(),0));
            
            //Set label to previewIcon.
            ListingImageLabel.setIcon(previewIcon);
        }
        else
        {   
            ListingImageLabel.setText("Image Missing");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JLabel ListingDescLabel;
    private javax.swing.JLabel ListingImageLabel;
    private javax.swing.JLabel ListingNameLabel;
    private javax.swing.JLabel ListingPriceLabel;
    // End of variables declaration//GEN-END:variables
}
