/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shamazon;

import javax.swing.JFrame;
import javax.swing.JTabbedPane;

/**
 *
 * @author Charles
 */
public class ShamazonApplication extends javax.swing.JFrame
{

    /**
     * Creates new form ShamazonApplication
     */
    public ShamazonApplication(UserAccount user)
    {
        initComponents();
        JFrame mainFrame = new JFrame();
        mainFrame.setSize(800, 600);
        
        JTabbedPane tabPane = ShamazonTab;
        tabPane.setSize(800, 600);
       
        ShoppingCart theCart = new ShoppingCart();
        TransactionManager tranMan = new TransactionManager(user);  
        
        ListingBrowser listBrow = new ListingBrowser(theCart, user);
        tabPane.addTab("Browse",listBrow);
        listBrow.setVisible(true);
        
        ShoppingCartPanel shopCartPan = new ShoppingCartPanel(theCart, tranMan);
        tabPane.addTab("Checkout",shopCartPan);
        shopCartPan.setVisible(false);
        
        mainFrame.add(tabPane);
        mainFrame.setVisible(true);
        tabPane.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        ShamazonTab = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShamazonTab, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShamazonTab, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ShamazonTab;
    // End of variables declaration//GEN-END:variables
}
